### ISSUE TITLE
Utils.c is missing declaration for rc variable.

### ISSUE THREAD

**Issue by gin-nader** [IBM/OpenJCEPlus#242]
The Util.c file makes use of the `rc` variable, but does not define `rc` anywhere https://github.com/IBM/OpenJCEPlus/blob/java17/src/main/native/Utils.c#L202

`rc` should be declared as an `int` before being assigned a value.

**Comment by farshadasl** [comment]
@gin-nader 
This is z/OS specific.

Could you please create a PR for it?

Thanks
