### ISSUE TITLE
Change permissions of buildNative* files

### ISSUE THREAD

**Issue by KostasTsiounis** [IBM/OpenJCEPlus#3]
At the moment, when cloning the repository, one has to manually change permissions in `buildNative*` files for the build process to work. We should change those permissions to allow execution out of the box.

**Comment by jasonkatonica** [comment]
Hi @KostasTsiounis I believe that this issue can now be closed since https://github.com/IBM/OpenJCEPlus/pull/7 has been merged.

**Comment by KostasTsiounis** [comment]
Yes. Issue has been resolved with https://github.com/IBM/OpenJCEPlus/pull/7.
